dbt_training:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: dbt_testdev
      user: "{{ env_var('DBT_USER') }}"
      host: localhost
      port: 8123
    ci:
      type: clickhouse
      schema: dbt_ci
      user: "{{ env_var('DBT_USER') }}"
      host: localhost
      port: 8123
    prod:
      type: clickhouse
      schema: dbt_prod
      user: "{{ env_var('DBT_USER') }}"
      host: localhost
      port: 8123
  target: dev
