name: Scheduled Prod Run

on:
#  schedule:
#    - cron: '0 8 * * *'

  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dbt
        run: pip3 install dbt-clickhouse

      - name: Install packages
        run: dbt deps

      - name: Deploy & Test Models (PROD)
        run: dbt build --profiles-dir . --target prod
